### ISSUE TITLE
Multiple pandas-profiling versions listed in requirements.txt

### ISSUE THREAD

**Issue by k-tamura** [sinanuozdemir/feature_engineering_bookcamp#2]
Multiple _pandas-profiling_ versions listed in _requirements.txt_. This causes:

> $ pip install -r feature_engineering_bookcamp/requirements.txt
>  ...
> ERROR: Cannot install pandas-profiling==3.0.0 and pandas-profiling==3.1.0 because these package versions have conflicting dependencies.
> 
> The conflict is caused by:
>     The user requested pandas-profiling==3.0.0
>     The user requested pandas-profiling==3.1.0
> 
> To fix this you could try to:
> 1. loosen the range of package versions you've specified
> 2. remove package versions to allow pip attempt to solve the dependency conflict

**Comment by sinanuozdemir** [comment]
Thanks for making the PR
